### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mickar** [stuartherbert/php-xxhash#4]
Hello,

I would like to use your code, but I haven't seen the license file.
XXHash is licensed under the BSD 2-Clause License.
I assume that your code is also under this license?
Maybe it will be better to create a license file.

thank you,
Best regards,

**Comment by stuartherbert** [comment]
Hello!

The README clearly states that the code is under the BSD 2-Clause license.

If you’re looking to use this extension with PHP, xxhash is (I believe) natively supported by PHP’s hash function now.
